//! The standardized message set every device emits into the
//! [`SynthController`](crate::SynthController).
//!
//! A device (Nintendo DS, GBA, …) parses its own ROM/archive formats, runs its own sequencer
//! and envelope hardware emulation, and communicates with the synthesis layer exclusively
//! through [`SynthEvent`]s. The controller owns the voice pools and the mixer; it never reads
//! device state directly. The reverse direction — facts only the synthesizer knows, like a
//! one-shot sample running out or a voice being stolen — flows back as [`TickFeedback`].

use std::sync::Arc;

use crate::waveform::Waveform;

/// Device-chosen identifier for one sounding voice. Unique for the lifetime of a player
/// (a simple monotonic counter); never reused, so stale references are unrepresentable.
pub type VoiceId = u64;

/// What pitch a voice plays at.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum VoicePitch {
    /// A MIDI note (possibly fractional), relative to the pitch the sample represents.
    /// The playback ratio is `note_hz(note) / sample_pitch_hz`, honoring the configured
    /// tuning system. This is how the DS expresses pitch.
    Midi {
        /// The (possibly fractional) MIDI note to sound.
        note: f64,
        /// The pitch (Hz) the sample data represents at its recorded rate.
        sample_pitch_hz: f64,
    },
    /// Play the sample data at an absolute rate of `hz` data-samples per second, ignoring the
    /// sample's recorded rate. This is how the GBA expresses pitch: its mixer steps the wave
    /// data at `frequency` Hz directly.
    DataRateHz(f64),
}

/// A control message generated by a device player for the [`SynthController`] to act on.
///
/// [`SynthController`]: crate::SynthController
#[derive(Debug, Clone)]
pub enum SynthEvent {
    /// Start a voice on `track`.
    NoteStarted {
        track: usize,
        /// Device-assigned id used by later events addressing this voice.
        voice: VoiceId,
        /// The sounding MIDI key (drives the visualizer grid).
        key: u8,
        /// The waveform to play.
        waveform: Arc<Waveform>,
        /// Initial pitch.
        pitch: VoicePitch,
        /// Initial linear volume (0..=1).
        volume: f64,
        /// Scheduled length in device ticks, if known (`None` = until released). Informational —
        /// used by look-ahead visualizers; the device itself ends the note with later events.
        duration_ticks: Option<u32>,
    },
    /// Update a voice's volume (devices re-evaluate envelopes every tick).
    VoiceVolume {
        track: usize,
        voice: VoiceId,
        volume: f64,
    },
    /// Update a voice's pitch.
    VoicePitch {
        track: usize,
        voice: VoiceId,
        pitch: VoicePitch,
    },
    /// Per-voice pitch offset in semitones on top of the base pitch (DS vibrato LFO).
    VoiceDetune {
        track: usize,
        voice: VoiceId,
        semitones: f64,
    },
    /// Stop a voice and free its slot (envelope hit the floor / channel cut).
    VoiceStopped { track: usize, voice: VoiceId },
    /// The note is no longer held (release began): clears the visualizer grid while the
    /// release tail keeps sounding.
    NoteReleased { track: usize, key: u8 },
    /// Track-wide stereo pan gains: `pan_vol_l`/`pan_vol_r` are the left/right pan-split gains the
    /// device frontend's pan law produced (a normalized split, ~sums to 1).
    TrackPan {
        track: usize,
        pan_vol_l: f64,
        pan_vol_r: f64,
    },
    /// Track-wide pitch offset in semitones (DS pitch-bend wheel).
    TrackDetune { track: usize, semitones: f64 },
    /// The MP2K reverb amount for the current song (0..=127, hardware `soundInfo.reverb` units).
    /// The controller applies it as a mono-summing feedback delay on the sampled bus; only the
    /// GBA emits this. `0` disables the reverb stage.
    ReverbAmount { amount: u8 },
    /// The sequence jumped backward (loop point) — used for loop counting.
    Looped,
    /// Every track has ended; the song is over.
    Ended,
}

/// Synthesizer-side facts reported back to the device player each tick: voices that stopped
/// without the device asking (round-robin steals, one-shot samples that ran out).
#[derive(Debug, Default)]
pub struct TickFeedback {
    /// `(track, voice)` pairs that ended since the last tick.
    pub ended_voices: Vec<(usize, VoiceId)>,
}

impl TickFeedback {
    /// Whether `voice` on `track` was reported ended.
    pub fn is_ended(&self, track: usize, voice: VoiceId) -> bool {
        self.ended_voices.contains(&(track, voice))
    }
}
