//! The standardized message set every device emits into the
//! [`SynthController`](crate::SynthController).
//!
//! A device (Nintendo DS, GBA, …) parses its own ROM/archive formats, runs its own sequencer
//! and envelope hardware emulation, and communicates with the synthesis layer exclusively
//! through [`SynthEvent`]s. The controller owns the voice pools and the mixer; it never reads
//! device state directly. The reverse direction — facts only the synthesizer knows, like a
//! one-shot sample running out or a voice being stolen — flows back as [`TickFeedback`].

use std::sync::Arc;

use crate::sample::Sample;

/// Device-chosen identifier for one sounding voice. Unique for the lifetime of a player
/// (a simple monotonic counter); never reused, so stale references are unrepresentable.
pub type VoiceId = u64;

/// What pitch a voice plays at.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum VoicePitch {
    /// A MIDI note (possibly fractional), relative to the pitch the sample represents.
    /// The playback ratio is `note_hz(note) / sample_pitch_hz`, honoring the configured
    /// tuning system. This is how the DS expresses pitch.
    Midi {
        /// The (possibly fractional) MIDI note to sound.
        note: f64,
        /// The pitch (Hz) the sample data represents at its recorded rate.
        sample_pitch_hz: f64,
    },
    /// Play the sample data at an absolute rate of `hz` data-samples per second, ignoring the
    /// sample's recorded rate. This is how the GBA expresses pitch: its mixer steps the wave
    /// data at `frequency` Hz directly.
    DataRateHz(f64),
}

/// The fixed-rate output chain of a device's sound hardware, declared by the device player and
/// reproduced per voice by [`ResampleMode::Authentic`](crate::ResampleMode::Authentic):
///
/// ```text
/// source data ──(linear interp)──► mixer_hz ──(nearest-neighbour hold)──► dac_hz ──(proper SRC)──► output
/// ```
///
/// PSG waveform channels bypass the software mixer on every device — they are
/// nearest-neighbour sampled straight at `dac_hz`.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct HardwareChain {
    /// The software-mixer rate sampled voices are linear-interpolated to (GBA: the
    /// `SOUND_MODE_FREQ_13379` engine rate). `None` when the hardware resamples each channel
    /// directly at the DAC rate (DS).
    pub mixer_hz: Option<f64>,
    /// The DAC output rate the mixer/PSG streams are held at (both consoles: 32768 Hz).
    pub dac_hz: f64,
}

/// A control message generated by a device player for the [`SynthController`] to act on.
///
/// [`SynthController`]: crate::SynthController
#[derive(Debug, Clone)]
pub enum SynthEvent {
    /// Start a voice on `track`.
    NoteStarted {
        track: usize,
        /// Device-assigned id used by later events addressing this voice.
        voice: VoiceId,
        /// The sounding MIDI key (drives the visualizer grid).
        key: u8,
        /// The waveform to play.
        sample: Arc<Sample>,
        /// Initial pitch.
        pitch: VoicePitch,
        /// Initial linear volume (0..=1).
        volume: f64,
        /// Scheduled length in device ticks, if known (`None` = until released). Informational —
        /// used by look-ahead visualizers; the device itself ends the note with later events.
        duration_ticks: Option<u32>,
    },
    /// Update a voice's volume (devices re-evaluate envelopes every tick).
    VoiceVolume {
        track: usize,
        voice: VoiceId,
        volume: f64,
    },
    /// Update a voice's pitch.
    VoicePitch {
        track: usize,
        voice: VoiceId,
        pitch: VoicePitch,
    },
    /// Per-voice pitch offset in semitones on top of the base pitch (DS vibrato LFO).
    VoiceDetune {
        track: usize,
        voice: VoiceId,
        semitones: f64,
    },
    /// Stop a voice and free its slot (envelope hit the floor / channel cut).
    VoiceStopped { track: usize, voice: VoiceId },
    /// The note is no longer held (release began): clears the visualizer grid while the
    /// release tail keeps sounding.
    NoteReleased { track: usize, key: u8 },
    /// Track-wide stereo pan (0 = left … 1 = right).
    TrackPan { track: usize, pan: f64 },
    /// Track-wide pitch offset in semitones (DS pitch-bend wheel).
    TrackDetune { track: usize, semitones: f64 },
    /// The sequence jumped backward (loop point) — used for loop counting.
    Looped,
    /// Every track has ended; the song is over.
    Ended,
}

/// Synthesizer-side facts reported back to the device player each tick: voices that stopped
/// without the device asking (round-robin steals, one-shot samples that ran out).
#[derive(Debug, Default)]
pub struct TickFeedback {
    /// `(track, voice)` pairs that ended since the last tick.
    pub ended_voices: Vec<(usize, VoiceId)>,
}

impl TickFeedback {
    /// Whether `voice` on `track` was reported ended.
    pub fn is_ended(&self, track: usize, voice: VoiceId) -> bool {
        self.ended_voices.contains(&(track, voice))
    }
}
