//! Mother 3 (GBA game code `A3UJ`, MOTHER 3 fan translation) song titles.
//!
//! English Sound Player track names from the MOTHER 3 Fan Translation
//! (`translation-tools/musicnames.txt`), paired with the real MP2K song id each plays. The Sound
//! Player does **not** list songs in song-id order — it uses a curated order via an in-ROM
//! slot→song-id table (a 12-byte-record array at file offset 0xecd42, song id at record offset 0,
//! anchored by slot 0xF8 "Curtain Call" = song #1518). This array is in that Sound Player order, so
//! an entry's index is its "Default" listing order; the game's many unnamed SFX/voice songs follow.

/// `(song_id, title)` in Sound Player order (the in-game music player's own order, *not* song-id
/// order). Only the 250 music tracks the Sound Player names are listed.
pub const SONGS: &[(u32, &str)] = &[
    (58, "Let's Begin!"),
    (40, "Fun Naming"),
    (246, "Voice 1101"),
    (1511, "Welcome!"),
    (253, "Alec's Log House"),
    (62, "Mom's Hometown"),
    (84, "Save"),
    (1519, "I'm a Mole Cricket!"),
    (1940, "Enemy Encounter!"),
    (1959, "Bothersome Guys"),
    (1943, "You Won!"),
    (3, "Stand Up Strong"),
    (83, "As You Wish"),
    (48, "A Letter to You, Honey"),
    (1513, "Carrier Pigeon"),
    (647, "Mysterious Flying Object"),
    (71, "LOG-O-TYPE"),
    (11, "F-F-Fire!"),
    (112, "Chapter 1"),
    (33, "Sound of Siren"),
    (120, "Together"),
    (10, "To Sunshine Forest"),
    (36, "Forest Prayer Sanctuary"),
    (72, "Forest of Flames"),
    (1942, "The Enemy Attacks!"),
    (1406, "Mr. Batty Twist"),
    (42, "The Water's Great"),
    (109, "Enter the Pigmasks!"),
    (1965, "Dangerous Guys"),
    (1947, "Troublesome Guys"),
    (110, "What?"),
    (1955, "Back Beat Battle"),
    (34, "Gentle Rain"),
    (74, "Homely Yado Inn"),
    (432, "Letter from You, My Sweet"),
    (75, "Hard Rain"),
    (119, "Let's Go Together!"),
    (8, "Run, My Dog, Run!"),
    (77, "Somewhere, Someday"),
    (203, "Got a..."),
    (66, "Cautiously"),
    (1149, "Mischievous Blues"),
    (1952, "Tragic Reconstruction"),
    (45, "Confusion"),
    (32, "MOTHER 3 Love Theme"),
    (78, "Sorrowful Tazmily"),
    (123, "Lonely Room"),
    (76, "In the Room"),
    (79, "Going Alone"),
    (37, "Fun Bazaar"),
    (400, "The Bread's Ready!"),
    (167, "Beyond the Sunshine Forest"),
    (1949, "More Mischievous Blues"),
    (1951, "Cumbersome Guys"),
    (1964, "Mambo de Battle"),
    (252, "With My Father-in-Law"),
    (1954, "Astonishing March"),
    (47, "Magypsy Party"),
    (43, "Much Better!"),
    (136, "Danger"),
    (1147, "More Troublesome Guys"),
    (1154, "Toppling March"),
    (1941, "Big Enemy Encounter!"),
    (1948, "Fight with Mecha-Drago"),
    (1104, "Victorious..."),
    (1945, "Level Up!"),
    (422, "Long Shadow"),
    (113, "Chapter 2"),
    (64, "Passing Down Secrets"),
    (168, "Mind of a Thief"),
    (1543, "Suspicious Flying Object"),
    (199, "Huh?"),
    (1953, "Zombeat"),
    (1153, "Tough Zombeat"),
    (1957, "Fate"),
    (1958, "Accelerondo"),
    (1151, "More Cumbersome Guys"),
    (67, "Osohe Castle"),
    (1165, "More Dangerous Guys"),
    (1155, "Back Beat Battle - Hard"),
    (1963, "And El Mariachi"),
    (1960, "Dry Guys"),
    (1397, "Etude for Ghosts"),
    (201, "Got Somethin' Good!"),
    (6, "Ragtime Osohe"),
    (1164, "Mambo de Battle Plus"),
    (1157, "Serious"),
    (410, "Unfounded Revenge"),
    (68, "Polterg-g-g-geist"),
    (1961, "Family Matters: 2nd Movement"),
    (69, "The Room Too Mysterious"),
    (104, "Fanfare of the Noble Spittoon"),
    (12, "Morning Already"),
    (65, "A Master, a Father, a Thief"),
    (1950, "Piggy Guys"),
    (1150, "Piggy Something"),
    (61, "Open Sesame Oil!"),
    (70, "Open Sesame Tofu!"),
    (1946, "Learned PSI!"),
    (1161, "Ode to Ancestors: 8th Movement"),
    (1962, "Formidable Foe"),
    (421, "Butch and the Villagers"),
    (171, "Chapter 3"),
    (170, "Monkey's Love Song"),
    (114, "We're Going Together...?"),
    (172, "Bean Bean Pork Bean"),
    (174, "BzZzT! Even In My Dreams!"),
    (175, "The Peddler's Grand Speech"),
    (173, "Monkey's Delivery Service"),
    (176, "Dance!"),
    (1549, "What Happened?!"),
    (177, "Laugh! Be Happy!"),
    (1162, "Formidable Foes"),
    (407, "Audacious March"),
    (423, "Drago!?"),
    (424, "Thanks, Drago!"),
    (401, "Something Strange is Going On"),
    (430, "Love Theme (Reprise)"),
    (431, "Chapter 4"),
    (121, "A Railway in Our Village!"),
    (80, "Good Morning"),
    (429, "Reminded"),
    (178, "Hotel Yado"),
    (179, "My Wonderful Room"),
    (180, "Fun Shopping"),
    (122, "Happy Town?"),
    (46, "A Little Elegy"),
    (127, "What's Beyond the Tunnel?"),
    (1160, "Even Drier Guys"),
    (49, "Murasaki Forest"),
    (394, "Whew, Hauling is Hard Work"),
    (1906, "Good Work"),
    (1158, "Stringendo"),
    (158, "Ride the Ropeway"),
    (124, "Club Titiboo Theme"),
    (5, "Big Shot's Theme"),
    (128, "Girl's Room"),
    (1515, "Shower Time Ballad"),
    (137, "The Attic's a Dungeon?!"),
    (408, "Intense Guys"),
    (399, "A 16-Beat Attack!"),
    (398, "A Marching Attack!"),
    (169, "Rock and Roll (Mild)"),
    (1169, "Rock and Roll (Spicy)"),
    (125, "Lucky's Room"),
    (9, "Bon Voyage, Amigo"),
    (38, "What's That?!"),
    (433, "Chapter 5"),
    (395, "Oh No!"),
    (166, "Dangerous Highway"),
    (428, "Pork Bean Outta Gas"),
    (149, "Parking Area: Dur-T Cafe"),
    (1914, "White (Owner's Recommendation)"),
    (1912, "Fairies (Neckbeard's Recommend.)"),
    (1916, "Resolve (Gum Guy's Recommend.)"),
    (24, "Blessing (Skinhead's Recommend.)"),
    (2, "Adolescence (Toilet Cow's Rec.)"),
    (409, "Wasteful Anthem"),
    (130, "His Highness' Playroom"),
    (159, "His Highness' Memory: 2S"),
    (160, "His Highness' Memory: 2H"),
    (425, "MROB-6720M"),
    (1425, "GENE163-1425"),
    (426, "Aria of Unease"),
    (419, "Chapter 6"),
    (29, "Sunflowers and Illusions"),
    (162, "Name These Children"),
    (50, "Mother?!"),
    (53, "A Tiny, Enormous Miracle"),
    (418, "Chapter 7"),
    (44, "Right Left Light Reft"),
    (427, "Quite the River"),
    (35, "Magypsy's Home, Sweetie-Pie"),
    (54, "Magypsy's Gone, Cutie-Pie"),
    (435, "Razor and Lipstick"),
    (1163, "And Yet, El Mariachi"),
    (417, "Close Your Eyes, Sugar"),
    (16, "She Was Like a Sunflower"),
    (1512, "Let's Ride the Train!"),
    (1514, "The Green Train's Fun, Too!"),
    (106, "It's Chimera Research"),
    (117, "Pink Shell"),
    (420, "Pulling of the Needles"),
    (1407, "More Audacious March"),
    (28, "Mole Cricket Elder"),
    (85, "Snowman"),
    (18, "His Highness' Theme"),
    (1409, "Smashing Song of Praise"),
    (415, "A Flying Whatchamacallit"),
    (115, "Mr. What's-His-Nose"),
    (116, "Mr. Saturn Theme Z"),
    (1152, "Tragic Security"),
    (1410, "Hustle for Pride"),
    (141, "War of the Words"),
    (60, "we humming"),
    (52, "Volcano! Inferno!"),
    (434, "Fassad and Interpreter"),
    (1516, "Coffee Break"),
    (1904, "Got Somethin' Great!"),
    (59, "Beachcombing"),
    (27, "O2 in Love"),
    (26, "Tanetane Island"),
    (55, "Red-Green-Yellow-Yellow♪"),
    (142, "Is it Just Me Or Are You Gorgeous?"),
    (1956, "Strong One"),
    (20, "And Then There Were None"),
    (181, "Is Anyone There?"),
    (13, "Like Looking for Dropped Pickles"),
    (63, "Chupichupyoi for World Heritage"),
    (414, "Who?"),
    (1156, "Strong One (Masked Man)"),
    (144, "True Welcome!"),
    (143, "Life's an Inner Turn Radius"),
    (438, "NPC Loves You!"),
    (411, "Chapter 8"),
    (140, "Isn't This Such a Utopia?!"),
    (56, "Blip-Blip High Score"),
    (153, "No Eating Crackers in the Cinema"),
    (147, "Beauty and Tasty"),
    (145, "New Pork Bossa"),
    (152, "Absolutely Filthy Apartments"),
    (7, "Leder's Gymnopedie"),
    (151, "Afro Bam-Babam"),
    (25, "Hey, Brother! Gimme an A!"),
    (412, "Theme of DCMC"),
    (1967, "Samba de Cambo"),
    (39, "Hippos"),
    (150, "Rain, Followed by a Harem"),
    (129, "Refreshing Toilets"),
    (146, "Under Construction..."),
    (118, "Automated..."),
    (1408, "Even More Intense Guys"),
    (1547, "Mini-Porky's Entrance"),
    (156, "Try Kind of Hard!"),
    (1548, "And... Stop!"),
    (406, "Natural Killer Cyborg"),
    (161, "Time Passage"),
    (19, "A Certain Someone's Memories"),
    (17, "I Am Porky"),
    (405, "Porky's Porkies"),
    (1937, "Burst-In Rock 'n' Roll"),
    (404, "Master Porky's Theme"),
    (403, "Absolutely Safe Capsule"),
    (1938, "Battle Against the Masked Man"),
    (163, "Memory of Mother"),
    (1935, "It's Over"),
    (15, "Phantasmagoric"),
    (1518, "Curtain Call"),
    (14, "16 Melodies (Beginning)"),
    (51, "Memory of Life"),
];
