//! Pokémon Emerald (GBA game code `BPEE`) song titles.
//!
//! Titles follow the official "Pokémon Ruby, Pokémon Sapphire & Pokémon Emerald: Super Music
//! Collection". The array is in **listing order**: the songs that appear on the album come first,
//! in the album's track order, followed by everything else (FireRed/LeafGreen ports, Battle
//! Frontier themes, jingles, Gold/Silver/Crystal cameos) by song id. An entry's position in this
//! array is its "Default" sort order.
//!
//! Song ids are the MP2K song-table indices from pret/pokeemerald `include/constants/songs.h`.

/// `(song_id, title)` in listing order (album tracks first, then the rest). The array index is the
/// song's position in "Default" sort.
pub const SONGS: &[(u32, &str)] = &[
    (442, "Opening Movie: Double Battles"),
    (413, "Title Screen: Main Theme"),
    (414, "Introductions"),
    (405, "Littleroot Town"),
    (383, "Birch Pokémon Lab"),
    (415, "May"),
    (410, "H-Help Me!"),
    (474, "Battle! (Wild Pokémon)"),
    (353, "Victory! (Wild Pokémon)"),
    (359, "Route 101"),
    (363, "Oldale Town"),
    (400, "Pokémon Center"),
    (368, "Pokémon Healed"),
    (380, "Trainers' Eyes Meet (Youngster)"),
    (379, "Trainers' Eyes Meet (Lass)"),
    (476, "Battle! (Trainer Battle)"),
    (412, "Victory! (Trainer Battle)"),
    (367, "Level Up!"),
    (362, "Petalburg City"),
    (420, "Hurry Along"),
    (401, "Route 104"),
    (366, "Petalburg Woods"),
    (441, "Team Magma Appears!"),
    (475, "Battle! (Team Aqua / Team Magma)"),
    (424, "Victory! (Team Aqua / Team Magma)"),
    (399, "Rustboro City"),
    (435, "Trainers' School"),
    (431, "Crossing the Sea"),
    (427, "Dewford Town"),
    (407, "Trainers' Eyes Meet (Tuber)"),
    (433, "Slateport City"),
    (375, "Oceanic Museum"),
    (360, "Route 110"),
    (403, "Cycling"),
    (426, "Game Corner"),
    (390, "Win"),
    (391, "Lose"),
    (392, "Reel Time"),
    (389, "Jackpot"),
    (398, "Verdanturf Town"),
    (418, "Route 113"),
    (449, "Twins"),
    (437, "Fallarbor Town"),
    (425, "Cable Car"),
    (406, "Mt. Chimney"),
    (451, "Trainers' Eyes Meet (Hiker)"),
    (409, "Route 111"),
    (364, "Pokémon Gym"),
    (477, "Battle! (Gym Leader)"),
    (354, "Victory! (Gym Leader)"),
    (369, "Obtained a Badge!"),
    (372, "Obtained a TM!"),
    (365, "Surf"),
    (402, "Route 119"),
    (382, "Fortree City"),
    (361, "Route 120"),
    (453, "Interviewers"),
    (428, "Safari Zone"),
    (397, "Trainers' Eyes Meet (Gentleman)"),
    (408, "Lilycove City"),
    (373, "Museum"),
    (378, "Move Deleted"),
    (421, "Brendan"),
    (481, "Battle! (Brendan / May)"),
    (377, "Evolution"),
    (371, "Congratulations! Your Pokémon Evolved!"),
    (404, "Poké Mart"),
    (432, "Mt. Pyre"),
    (423, "Trainers' Eyes Meet (Psychic)"),
    (416, "Trainers' Eyes Meet (Hex Maniac)"),
    (434, "Mt. Pyre Exterior"),
    (430, "Hideout"),
    (370, "Obtained an Item!"),
    (419, "Team Aqua Appears!"),
    (483, "Battle! (Team Aqua / Team Magma Leaders)"),
    (388, "The Super-Ancient Pokémon Awaken!"),
    (444, "Drought"),
    (443, "Heavy Rain"),
    (411, "Dive"),
    (445, "Sootopolis City"),
    (386, "Cave of Origin"),
    (480, "Battle! (Super-Ancient Pokémon)"),
    (385, "Trainers' Eyes Meet (Swimmer)"),
    (422, "Ever Grande City"),
    (387, "Obtained a Berry!"),
    (452, "Contest Lobby"),
    (440, "Pokémon Contest!"),
    (446, "Results Announcement"),
    (439, "Contest Winner"),
    (438, "Sealed Chamber"),
    (479, "Battle! (Regirock / Regice / Registeel)"),
    (448, "The Trick House"),
    (381, "Abandoned Ship"),
    (384, "Battle Tower (Ruby & Sapphire)"),
    (429, "Victory Road"),
    (417, "Trainers' Eyes Meet (Cooltrainer)"),
    (450, "The Elite Four Appear!"),
    (482, "Battle! (Elite Four)"),
    (454, "Champion Steven"),
    (478, "Battle! (Steven)"),
    (355, "Victory! (Steven)"),
    (447, "Room of Glory"),
    (436, "The Hall of Fame"),
    (455, "Ending Theme"),
    (456, "The End"),
    (350, "Littleroot Town (Test Version)"),
    (351, "Route 38 (Gold & Silver)"),
    (352, "Pokémon Caught!"),
    (356, "Pokémon Communication Center (Crystal)"),
    (357, "Pewter City (Gold & Silver)"),
    (358, "Battle! (Legendary Beast) (Crystal)"),
    (374, "Route 122"),
    (376, "Evolution (Intro)"),
    (393, "Pokémon Contest! (Link, Movement 1)"),
    (394, "Pokémon Contest! (Link, Movement 2)"),
    (395, "Pokémon Contest! (Link, Movement 3)"),
    (396, "Pokémon Contest! (Link, Movement 4)"),
    (457, "Battle Frontier"),
    (458, "Battle Arena"),
    (459, "Obtained Battle Points!"),
    (460, "Match Call Registered"),
    (461, "Battle Pyramid"),
    (462, "Battle Pyramid (Summit)"),
    (463, "Battle Palace"),
    (464, "Rayquaza Appears"),
    (465, "Battle Tower"),
    (466, "Obtained a Symbol!"),
    (467, "Battle Dome"),
    (468, "Battle Pike"),
    (469, "Battle Factory"),
    (470, "Battle! (Rayquaza)"),
    (471, "Battle! (Frontier Brain)"),
    (472, "Battle! (Mew)"),
    (473, "Battle Dome Lobby"),
    (484, "Follow Me (FireRed & LeafGreen)"),
    (485, "Game Corner (Kanto)"),
    (486, "Team Rocket Hideout"),
    (487, "Pokémon Gym (Kanto)"),
    (488, "Jigglypuff's Song"),
    (489, "Opening Movie (FireRed & LeafGreen)"),
    (490, "Title Screen (FireRed & LeafGreen)"),
    (491, "Cinnabar Island"),
    (492, "Lavender Town"),
    (493, "Pokémon Healed (Kanto)"),
    (494, "Cycling (Kanto)"),
    (495, "Trainers' Eyes Meet (Team Rocket)"),
    (496, "Trainers' Eyes Meet (Girl, Kanto)"),
    (497, "Trainers' Eyes Meet (Boy, Kanto)"),
    (498, "Hall of Fame (Kanto)"),
    (499, "Viridian Forest"),
    (500, "Mt. Moon"),
    (501, "Pokémon Mansion"),
    (502, "Ending Theme (FireRed & LeafGreen)"),
    (503, "Route 1 (Kanto)"),
    (504, "Route 24 (Kanto)"),
    (505, "Route 3 (Kanto)"),
    (506, "Route 11 (Kanto)"),
    (507, "Victory Road (Kanto)"),
    (508, "Battle! (Gym Leader, Kanto)"),
    (509, "Battle! (Trainer, Kanto)"),
    (510, "Battle! (Wild Pokémon, Kanto)"),
    (511, "Battle! (Champion, Kanto)"),
    (512, "Pallet Town"),
    (513, "Oak Pokémon Lab"),
    (514, "Professor Oak"),
    (515, "Pokémon Center (Kanto)"),
    (516, "S.S. Anne"),
    (517, "Surf (Kanto)"),
    (518, "Pokémon Tower"),
    (519, "Silph Co."),
    (520, "Fuchsia City"),
    (521, "Celadon City"),
    (522, "Victory! (Trainer, Kanto)"),
    (523, "Victory! (Wild Pokémon, Kanto)"),
    (524, "Victory! (Gym Leader, Kanto)"),
    (525, "Vermilion City"),
    (526, "Pewter City"),
    (527, "Trainers' Eyes Meet (Rival)"),
    (528, "Rival's Departure"),
    (529, "Pokédex Evaluation"),
    (530, "Obtained a Key Item!"),
    (531, "Pokémon Caught! (Intro, Kanto)"),
    (532, "Photo"),
    (533, "Game Freak"),
    (534, "Pokémon Caught! (Kanto)"),
    (535, "New Game (Instructions)"),
    (536, "New Game (Intro)"),
    (537, "New Game (Exit)"),
    (538, "Pokémon Jump"),
    (539, "Union Room"),
    (540, "Pokémon Network Center"),
    (541, "Mystery Gift"),
    (542, "Berry Picking"),
    (543, "Sevii Islands (Cave)"),
    (544, "Teachy TV"),
    (545, "Sevii Islands (Route)"),
    (546, "Sevii Islands (Dungeon)"),
    (547, "Sevii Islands (1-3)"),
    (548, "Sevii Islands (4-5)"),
    (549, "Sevii Islands (6-7)"),
    (550, "Poké Flute"),
    (551, "Battle! (Deoxys)"),
    (552, "Battle! (Mewtwo)"),
    (553, "Battle! (Legendary Pokémon, Kanto)"),
    (554, "Trainers' Eyes Meet (Gym Leader, Kanto)"),
    (555, "Deoxys Appears"),
    (556, "Trainer Tower"),
    (557, "Pallet Town (Slow)"),
    (558, "Teachy TV (Menu)"),
];
