//! One SSEQ track: its registers and call stack.

#[derive(Debug, Clone)]
pub struct SequenceTrack {
    pub active: bool,
    pub bpm: u32,
    pub pc: u32,
    pub pan: i32,
    pub mono: bool,
    pub volume: i32,
    pub master_volume: i32,
    pub priority: i32,
    pub program: usize,
    pub bank: usize,
    pub lfo_type: i32,
    pub lfo_depth: i32,
    pub lfo_range: i32,
    pub lfo_speed: i32,
    pub lfo_delay: i32,
    pub pitch_bend: i32,
    pub pitch_bend_range: i32,
    pub expression: i32,
    pub portamento_enable: i32,
    pub portamento_time: i32,
    pub portamento_key: i32,
    pub transpose: i32,
    pub sweep_pitch: i32,
    pub note_wait: bool,
    pub muted: bool,
    pub tie: bool,
    pub note_finish_wait: bool,
    pub cmp: bool,
    pub resting_for: u32,
    pub stack: [u32; 64],
    pub loop_count: [u8; 64],
    pub sp: usize,
    pub attack_rate: i32,
    pub decay_rate: i32,
    pub sustain_rate: i32,
    pub release_rate: i32,
}

impl Default for SequenceTrack {
    fn default() -> Self {
        Self {
            active: false,
            bpm: 0,
            pc: 0,
            pan: 64,
            mono: false,
            volume: 127,
            master_volume: 127,
            priority: 64,
            program: 0,
            bank: 0,
            lfo_type: 0,
            lfo_depth: 0,
            lfo_range: 1,
            lfo_speed: 16,
            lfo_delay: 0,
            pitch_bend: 0,
            pitch_bend_range: 2,
            expression: 127,
            portamento_enable: 0,
            portamento_time: 0,
            portamento_key: 60,
            transpose: 0,
            sweep_pitch: 0,
            note_wait: true,
            muted: false,
            tie: false,
            note_finish_wait: false,
            cmp: true,
            resting_for: 0,
            stack: [0; 64],
            loop_count: [0; 64],
            sp: 0,
            attack_rate: 0,
            decay_rate: 0,
            sustain_rate: 0,
            release_rate: 0,
        }
    }
}
